name: TERRAFORM

on:
  push:
    branches: [ main ]
    paths:
    - 'terragrunt/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'terraform/**'

  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      ACCESS_CLIENT_SECRET: ${{secrets.ACCESS_CLIENT_SECRET}}

    defaults:
      run:
        working-directory: ./terragrunt/terragrunt.hcl
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: terragrunt Init
        run: terragrunt init

      - name: terragrunt Plan
        run: terragrunt plan

      - name: terragrunt Apply
        run: terragrunt apply -auto-approve